services:
  - type: web
    name: apikeymanagement
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

      # Database
      - key: DATABASE_URL
        value: 'postgresql://neondb_owner:npg_0RL5afcNplGy@ep-cool-credit-a1qfzj69-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'

      # Auth
      - key: JWT_SECRET_KEY
        generateValue: true

      # MAIL CONFIG
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM_ADDRESS
        value: no-reply@iamchuong.id.vn
      - key: EMAIL_FROM_NAME
        value: "SIMPLEBIM CONTACT"

      # CORS
      - key: CORS_ORIGINS
        value: "*"

      # Token & OTP
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: OTP_EXPIRE_MINUTES
        value: 1
